# Generated by Django 4.2.2 on 2023-06-14 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotels',
            old_name='image',
            new_name='hotel_image',
        ),
        migrations.RenameField(
            model_name='hotels',
            old_name='price',
            new_name='hotel_price',
        ),
    ]
